/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/E1dHBI6HZgu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import React from "react"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from "@/components/ui/select"

export function ModelSelect() {
  const [value, setValue] = React.useState("gpt4")
  return (
    (<Select value={value} onValueChange={setValue}>
      <SelectTrigger className="w-[180px]">
        <SelectValue placeholder="Select an AI model" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectItem value="gpt4">GPT-4o</SelectItem>
          <SelectItem value="gpt35">GPT-3.5</SelectItem>
        </SelectGroup>
      </SelectContent>
    </Select>)
  );
}
